# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=500)),
                ('order', models.IntegerField(default=10, help_text='The index order to place.')),
            ],
            options={
                'db_table': 'faq_tbl',
                'ordering': ['order'],
            },
        ),
    ]
