# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170912_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Denied'), (2, 'Accepted'), (3, 'Attending'), (4, 'Declined'), (5, 'Other')], default=0),
        ),
    ]
