# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='travel',
            field=models.BooleanField(default=False),
        ),
    ]
