# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:42
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.resume_loc),
        ),
    ]
